server:
  port: 8088
  servlet:
    context-path: /

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    druid:
    # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存时间
      min-evictable-idle-time-millis: 300000name

mybatis:
  mapper-locations: classpath:mapper/*.xml

JsonToSqlUtil:
  field: id,name,description,pictureUrl,url,testUrl,ttUrl,aaUrl,kakaka,createDate #数据字段名，按返回顺序写(英文,隔开)
  timeField: createDate,updateDate # 格式是时间的字段(英文,隔开)
  timeFieldType: false # 是否为时间戳格式 true or false
  tableName: data # 数据库表名
  primaryKey: id  # 主键名
  # 填写所需要数据data的路径 例如：{"store": { "data": [{"category": "reference"，"price": 8.95}，路径为：store.data
  dataPath: data
  # url
  url: http://localhost:8081/
  # 请求方式（post or get）
  method: post
  # 请求体，使用 '' 括起来,没有则留空
  body: ''
